### ISSUE TITLE
hello - api

### ISSUE THREAD

**Issue by GlauberF** [ruuvi/ruuvitracker_server#84]
Hello, how do I get the api and webapp code to manage my iBeacons?
Because your project is open source

**Comment by laurijamsa** [comment]
Hi,

This repository hasn't been maintained in 3 years. Because everything is open-source, please check more recent repositories which are related to RuuviTag project. Closing this issue.

**Comment by GlauberF** [comment]
Could you pass me the link from the new repository?

**Comment by laurijamsa** [comment]
https://github.com/ruuvi
